### ISSUE TITLE
Put placeholder in the name of bookmark field

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#117]
At the moment it's not clear that the name field is optional when saving a new bookmark and what's the default value.

The easier solution is to put placeholder in save field with the default system value: method name + request url

![Resting - the REST client - Mozilla Firefox_025](https://user-images.githubusercontent.com/4171821/94249780-a9bd1900-ff20-11ea-9d8f-d45b946ea079.png)

**Comment by KwanJunWen** [comment]
I'll try to work on this ya

**Comment by mirkoperillo** [comment]
Very good, thank you !

Il giorno ven 25 set 2020 alle ore 11:30 Kwan Jun Wen <
notifications@github.com> ha scritto:

**Comment by KwanJunWen** [comment]
Hi, wasn't sure if the implementation is correct. I've added the value computation if the request URL field is not empty. Otherwise it will fallback to the original selected bookmark name. 

@mirkoperillo Kindly take a look at the PR. Much thanks ! Btw, I couldn't get the test running and I am not sure if test changes need to be made.

**Comment by KwanJunWen** [comment]
@mirkoperillo Updated PR to display system default value as placeholder for bookmark name input. Request URL will be defaulted to `''` instead of `undefined` if is it an empty value.
