### ISSUE TITLE
Har import in a folder

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#140]
## Expected Behavior
When an user select to import an har file, this import should be possible inside a folder

## Actual Behavior
Right now if you are working with a set of http api rest call on firefox / chrome and export as har file, when you import them in resting, this made a mess, because all of them are imported in the root, not inside a folder.

for example:

![image](https://user-images.githubusercontent.com/12526457/153359039-ff658289-28ac-4fa8-861a-03372e175e23.png)

So my idea is to let user select a folder where import them or create a new one

## Steps to Reproduce the Problem

  1. open resting
  1. select to import an har file
  1. select an har file
  2. all the api call are in the "root" not inside one folder

## Specifications

  - Addon Version: 1.3.1
  - Firefox Version: 97.0
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
@albertotn, this is a bug, theoretically the bookmarks are to be imported in the related folder

So if you have exported the bookmark1 contained by Folder1, when you import the export you should have the Folder1 containing the bookmark1.

I'm going to work on this asap.
Thank for using and reporting about Resting

**Comment by mirkoperillo** [comment]
The problem hits folders with more than one bookmark. 
Only first bookmark is imported correctly in the folder, the others loose the folder reference during the import.

**Comment by mirkoperillo** [comment]
@albertotn you can find the fix of this issue in the last Resting version v1.4.1

**Comment by mirkoperillo** [comment]
@albertotn you expose a different scenario.
When you import an HAR archive exported from a browser (Firefox, Chrome etc), the archive contains a plain list of HTTP requests because the browsers don't have the concept of folders.

This fix is about the importing process of a previous exportation from Resting. 
So the covered  scenario is: "I export my stuff from Resting as backup and then I want to re-import it".

The export format used by Resting is the HAR standard extended with the concept of folders.

I hope this clarify better the fix.
