### ISSUE TITLE
Unexpected intial empty space viewing the raw response body

### ISSUE THREAD

**Issue by mirkoperillo** [mirkoperillo/resting#170]
An unexpected empty space is present at the beginning of the raw response body visualization

![Selezione_058](https://user-images.githubusercontent.com/4171821/224559294-f96a6545-efc7-49f4-b767-42dcbfb3cfc4.png)

**Comment by nikhilraojl** [comment]
This seems to be an issue caused by white space in the `<pre>` tag
![image](https://user-images.githubusercontent.com/61220506/230020279-876ff4c6-988b-4bbf-921a-2c30bbdd08f5.png)

Using `white-space: normal` on `<pre class="pre-scrollable" ...` element should fix the issue

![image](https://user-images.githubusercontent.com/61220506/230020754-cf000c5e-aca1-4b3c-ae33-e8c80c8132d3.png)
Observe the white spaces in the inspector are automatically collapsed
