### ISSUE TITLE
Rename of a bookmark is not clear

### ISSUE THREAD

**Issue by alexmario74** [mirkoperillo/resting#77]
## Expected Behavior

You should be able to amend a saved bookmark and save it with a different name and preserving the old bookmark as it is.

Renaming a bookmark should be a specific change that involves only the bookmark name and no other attributes.

Consider if you have 2 environments development and production, and you just saved a request performed in production.

Now you want to do the same exact request in development to debug a bug you're working on. It would be nice to avoid rewrite all the details of such a request when you just need to change the server name or the port of the URL.

Consider that such a request are usually rich of data you have to set up, headers, authentication and body fields.

Manually rebuild the request can drive to have a slightly different request that is not longer reproduce your bug, or worst, that cover a much narrow bug and once you fixed, the original is still there, and you discover it in production, where you have the proper request.

## Actual Behavior

If you want to save a request you had obtained just amending an old one, already saved on a bookmark, it happened that it also rename and update the old bookmark instead of saving a new entry.

## Steps to Reproduce the Problem

  1. load a saved bookmark
  1. change some details
  1. press "Save" button
  1. change the name on the dialog and press "Save"

The old bookmark disappears.

## Specifications

  - Addon Version: 0.10
  - Firefox Version: 65.0.2
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
Hi,

I understand the scenario, actually Resting permits to satisfy it in two ways:
1. Use duplicate bookmark action ( available in contextual menu, right click on bookmark): in this case it's possible to clone the bookmark and modify target fields.
2. Use variables and contexts (available from Settings menu): so define one or more variables and use it instead of the target parts of request. In this case you can define a DEV and PROD context and bind it to the request with different values for defined variables.

Thank you for you feedback, it helps me to understand that:
1. Contextual menu and contexts aren't easy to find.
2. An explicit `Save as` button together with `Save` button can help the user

**Comment by alexmario74** [comment]
I see, so I can close this issue, thanks.
