### ISSUE TITLE
XML responses are not correctly visualized

### ISSUE THREAD

**Issue by albertotn** [mirkoperillo/resting#99]
## Expected Behavior
A rest service could not response always as json, so Resting should not assume response is a json.

## Actual Behavior
If I create a rest service that returns "Hello world" (without json, only the string) or xml, or something that is not json, response is not displayed or there is an error.

## Steps to Reproduce the Problem

  1. create a mock service using online service, like: https://www.mocky.io/ that does not response with application/json , for example application/xml, see:

![immagine](https://user-images.githubusercontent.com/12526457/67687574-cd868080-f998-11e9-9887-51c9c0edc00e.png)

  1. call it with resting, does not display response body:

![immagine](https://user-images.githubusercontent.com/12526457/67687545-c1022800-f998-11e9-9f85-93b7e27a12ec.png)

There are following errors on console too:
```

Errore interpretazione XML: errore di sintassi
Indirizzo: http://www.mocky.io/v2/5db6fce22f0000abb37febb0?_=1572273217237
Riga numero 1, colonna 1: 5db6fce22f0000abb37febb0:1:1
Errore interpretazione XML: errore di sintassi
Indirizzo: moz-extension://f42f159f-7b98-4a42-93ae-72e210f00d2d/index.html
Riga numero 1, colonna 1:
```

With my service (defined with swagger 2, javaEE no Spring):

```

			String res = "ok";
			return Response.ok().entity(res).build();
```

I got same result but different error:

![immagine](https://user-images.githubusercontent.com/12526457/67687850-31a94480-f999-11e9-8443-38e3541ba5d5.png)

## Specifications

  - Addon Version: 0.13.0
  - Firefox Version: 70.0
  - OS: Windows 10

**Comment by mirkoperillo** [comment]
@albertotn you are definitely right.
Resting considers that every response is a JSON response and this isn't right.

Resting should analyze the `Content-Type` header and process the response body with the correct format. 
At the moment the easiest solution is to check the response `Content-Type` and use the actual visualization if its value is `application/json`  otherwise consider it as raw text.

**Comment by mirkoperillo** [comment]
Hi @albertotn, 
I have tried to reproduce your problem on the last Resting version (v0.14.0) and Firefox 70 and using https://www.mocky.io/
It seems that the problem is only with responses with Content-Type `application/xml` or `text/xml`, so when the response it is declared as a XML.

In other cases like `text/plain` or others values, the response is visualized.
In my test XML responses are not correctly visualized but they don't generate any error in console.

I will try to go more deep in it.
